ARG VERSION=1

FROM alpine:latest AS certs
RUN apk add --no-cache ca-certificates

COPY ./SleepyNeko-Studios-Infra-Root-CA.crt /usr/local/share/ca-certificates/SleepyNeko-Studios-Infra-Root-CA.crt
RUN update-ca-certificates

# --------------------------------

FROM n8nio/n8n:${VERSION}

LABEL author="SleepyNeko Studios" maintainer="admin@sleepyneko.com"

USER root

RUN adduser -D -h /home/container -s /bin/sh container
ENV USER=container HOME=/home/container

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=certs /usr/local/share/ca-certificates/ /usr/local/share/ca-certificates/

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/SleepyNeko-Studios-Infra-Root-CA.crt
ENV N8N_USER_FOLDER="/home/container/.n8n"
# CVE-2025-68668
ENV N8N_PYTHON_ENABLED=false

USER container
WORKDIR /home/container

COPY --chown=container:container ./n8n/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
